#!/bin/sh
# ============================================================
# Estavo v3 — CSS build
#
# There is no bundler in this repo, so production CSS is a
# plain concatenation of the v3 modules in layer order.
# @import would cost a round trip per module on first paint;
# concatenating keeps it to one request.
#
# Usage:  sh tools/build-css.sh
# Output: assets/css/estavo-v3.css
# ============================================================
set -e

cd "$(dirname "$0")/.."

SRC="assets/css/v3"
OUT="assets/css/estavo-v3.css"

{
  echo "/* Estavo v3 — generated by tools/build-css.sh. Do not edit."
  echo "   Edit the modules in assets/css/v3/ and rebuild. */"
  echo "@layer reset, tokens, base, layout, components, motion, utilities;"
  echo ""

  for module in tokens base layout controls header-footer components illustrations motion utilities responsive premium; do
    echo "/* ── $module ───────────────────────────────────── */"
    cat "$SRC/$module.css"
    echo ""
  done
} > "$OUT"

echo "built $OUT"
wc -c "$OUT"
